use_frameworks!

platform :ios, '12.0'

target 'GGTableView_Example' do
  pod 'GGTableView', :path => '../'
  pod 'SnapKit', '~> 5.0.0'

  target 'GGTableView_Tests' do
    inherit! :search_paths

    
  end
end
